fix-atoms
hoangthai1997/Homework-17--css__atomic pull request #9
Opened 2021-03-05 08:20 UTC by hoangthai1997

2021-03-05 08:22 UTC, hoangthai1997 commented
fix atoms

2021-03-07 01:42 UTC, kenle reviewed
Please check review

2021-03-07 01:42 UTC, kenle commented on css/0-base.css
>    font-family: "roboto condensed", "sans-serif" !important;
```css
font-family: "roboto condensed", "sans-serif";
````

1) Avoid using important.  CSS is read top to bottom.  Anything on the bottom usually has higher priority than the top.  For example:
```css
font-size: 12px;
font-size: 14px;
```
The font size will be 14px in this case.

"important" is dangerous because:

For example:
```css
font-size: 12px !important;
font-size: 14px;
```

Font size will still be 12px.  14px cannot override "!important".

2021-03-08 00:09 UTC, kenle requested changes
**step1-atom-index.html**
line 11-13
```html
    <link rel="stylesheet" href="./css/0-base.css" />
    <link rel="stylesheet" href="./css/0-reset.css" />
    <link rel="stylesheet" href="./css/step1-atom.css" />
```
You have to realize CSS is read top to bottom by the web browser.  Meaning anything at the bottom will override anything up top.  
1) What is the purpose of reset.css?
2) What is the purpose of base.css?
3) Are they in the proper order?
4) Open **step1-atom-index.html** in a browser, is it displaying proper font?
5) Please always check your work in the browser.  Really important when going to work.  If it does not appear right, you need to figure out why and fix!  Don't show your boss work before you checked your work carefully in the browser!
6) Please fix lines 11-13 based on answers to 1,2,3,4,5.
7) Please check all other atoms in the browser.  Is each atom displaying correctly compared to the real design?  Please fix all again carefully, check your work, then ask me to check again.

2021-03-08 00:28 UTC, kenle requested changes
@hoangthai1997 Like the previous comment mentioned, please check all your atoms carefully visually.  Make sure they all look exactly like the design.  Really important when you go to work, make sure to check visually in the web browser.

A good tool we use in workplace to check our design is called "pixel perfect".
https://www.youtube.com/watch?v=s9r9HlL-ShM

1) Please install "pixel perfect" chrome extension.

2) Install "GoFullPage"  chome extension

3) Take a screenshot of the real design with "GoFullPage"

4) Open **step1-atom-index.html** page, open "pixel perfect" and load in the screenshot on this page.  Overlay the design onto each atom to see if it matches the design. 

5) We can Google Meeting sometime for me to show you this tool.

2021-03-08 00:28 UTC, kenle commented on css/step1-atom.css
>    color: #fff;
```suggestion
  color: #fff;
  display: inline-block;
```

1.  As the previous comment, please visually check your work in the web browser.  This atom does not display properly without `display: inline-block`.  It's ok to use `display` on atoms if needed.  On the other hand you rarely want to use `position` in atoms since it is related to layout.
2. What is the default `display` for `<a>` tags?  `display: inline`, `display: inline-block`, or `display: block`?  In other words, if you don't specify `display` style for an `<a>` tag what is the default?
3. What is the difference between `display:inline`, `display: inline-block`, and `display: inline-block`?  Please explain.

2021-03-10 06:21 UTC, kenle commented
> **step1-atom-index.html**
> line 11-13
> 
> ```
>     <link rel="stylesheet" href="./css/0-base.css" />
>     <link rel="stylesheet" href="./css/0-reset.css" />
>     <link rel="stylesheet" href="./css/step1-atom.css" />
> ```
> 
> You have to realize CSS is read top to bottom by the web browser. Meaning anything at the bottom will override anything up top.
> 
> 1. What is the purpose of reset.css?
> 2. What is the purpose of base.css?
> 3. Are they in the proper order?
> 4. Open **step1-atom-index.html** in a browser, is it displaying proper font?
> 5. Please always check your work in the browser.  Really important when going to work.  If it does not appear right, you need to figure out why and fix.  Last time you put "important" so that the font would display properly, but that is not the proper fix.
> 6. Please fix lines 11-13 based on answers to 1,2,3,4,5.
> 7. Please check all other atoms in the browser.  Is each atom displaying correctly compared to the real design?  Please fix all again carefully, check your work, then ask me to check again.
> 
> **Special Note:**
> Really important when you go to work. Always remember to check your code, and also to check how it looks in the web browser before sending your work to your boss. If something does not look right, try to fix it or ask someone with knowledge how to do it.

@hoangthai1997 Plese answer questions above and fix.

2021-03-10 06:21 UTC, kenle commented
> @hoangthai1997 Like the previous comment mentioned, please check all your atoms carefully visually. Make sure they all look exactly like the design. Really important when you go to work, make sure to check visually in the web browser.
> 
> A good tool we use in workplace to check our design is called "pixel perfect".
> https://www.youtube.com/watch?v=s9r9HlL-ShM
> 
> 1. Please install "pixel perfect" chrome extension.
> 2. Install "GoFullPage"  chome extension
> 3. Open the real design in web browser, take a screenshot of the real design with "GoFullPage"
> 4. Open **step1-atom-index.html** page, open "pixel perfect" and load in the screenshot (jpg or png) on this page.  Overlay the design onto each atom to see if it matches the design.
> 5. We can Google Meeting sometime for me to show you this tool.

@hoangthai1997 Please fix all atoms to look like design.

2021-03-20 07:25 UTC, hoangthai1997 commented
@kenle

2021-04-07 02:52 UTC, closed without merging